// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjkijjrtwotakncztgnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqa2lqanJ0d290YWtuY3p0Z25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTAxMTEsImV4cCI6MjA2MTA4NjExMX0.ny0rm4z5cAvBIA38EyJwLu5y98lLvk7aTKLnyNhkFzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);